### PR TITLE
Support Celery 4.2 RC

### PR DESCRIPTION
**Pull request by tedmiston**
_Note: Not yet tested._

This flexes our Celery dependency requirement to add support for more future versions.  The next release of Celery (4.2) is coming very soon.

Requested by a user via https://github.com/astronomerio/incubator-airflow/pull/23#issuecomment-382775677.

Issue - https://github.com/astronomerio/astronomer/issues/59

@schnie Are you cool with this?

### CODE REVIEW

**Comment by schnie** [comment]
Assuming this is for an EE user right? What does this get us?

**Comment by tedmiston** [comment]
Not a current EE user that I'm aware of.

This lets people use newer versions of Celery installed beyond 4.0.2, including pre-release versions.  It's common to add the major version exclusive upper bound to a package in a setup.py so that whenever Celery 5 is released, it won't potentially start breaking for new users.

**Comment by schnie** [comment]
Well, I'm more asking what does a newer version of Celery get us for Airflow. Is there any reason to update other than a newer version being released, or does this get us something that we need?

**Comment by tedmiston** [comment]
I haven't looked into the upcoming release yet, but there's not a specific feature we need or anything like that.  Just trying to stay on the edge.

**Comment by schnie** [comment]
Unless we're planning on sending this as a PR to Apache, then I think we should just close this. If a user wants to try an untested version of an airflow dependency, that change should happen in their own `Dockerfile`. I don't want our fork to have too many one off changes that won't make it upstream.

**Comment by schnie** [comment]
@tedmiston so are you going to send a PR back to Apache if we merge this? Fokko will merge it? We should definitely test it before sending it.

**Pull request closed without merging**
