### PR TITLE
Pin Celery to 4.0.2

### PR DESCRIPTION
**Pull request by tedmiston**

### CODE REVIEW

**Comment by schnie** [comment]
LGTM

**Comment by tedmiston** [comment]
@cloneluke Any chance you know when the RC will graduate to an official release?

**Comment by cloneluke** [comment]
No ETA, but soon according to this: https://github.com/celery/celery/issues/4387

https://github.com/celery/celery/milestone/19

**Comment by tedmiston** [comment]
@cloneluke Cool - I'll put up a PR for it.  You can follow https://github.com/astronomerio/astronomer/issues/59 if you'd like to track when it's tested + merged.

**Comment by ryw** [comment]
@schnie @tedmiston what is next step on this?

**Comment by ryw** [comment]
nevermind, see that it's closed :)

**Pull request merged**
