### PR TITLE
Adding support for dictionary int attr in templating

### PR DESCRIPTION
**Pull request by andscoop**
Add support for integer types in dictionaries passed to Operators that will be traversed for templating. Previously would return error, now returns integer in it's original form inline with the dict traversal.

### CODE REVIEW

**Comment by tedmiston** [comment]
@andscoop I have a couple q's:

0. Can you remind me on the use case for this?
0. Do we know if it breaks backwards compatibility?
0. Do we have interest in upstreaming this?

**Comment by andscoop** [comment]
0.) I want to pass in a jina templated dictionary object to be consumed by pyMongo for .aggregate() and .find(). It works for most use cases - returning dictionary values for strings - but it breaks where dict value is an integer. That forces the user to decide between a totally templated dict or an untemplated dict being passed in. I need partial templating ability (mixing int and strings).

1.) This should not break backwards compatibility as it only increases the feature set of airflow templating and does not decrease or modify existing features.

2.) I think we are going to NEED to upstream this if we are going to upstream the MongoHook that I have written.

Please see [306](https://github.com/astronomerio/engineering/issues/306) for original issue I opened.

**Comment by andscoop** [comment]
@tedmiston if you agree with changes let's get this in the docker-airflow-saas in the next couple of days - as I will be needing it for a caliberMind customer DAG.

**Comment by bonominijl** [comment]
@tedmiston Is this something we can get merged? Currently blocked on Calibermind until this gets in, assuming you sign off.

**Comment by tedmiston** [comment]
@andscoop @bonominijl LGTM - Feel free to merge.  Note the implications of changing the docker tag for running customers in prod that we discussed - https://astronomerteam.slack.com/archives/C4CPUELPP/p1505857330000014.

**Comment by ryw** [comment]
@abrongersma we prob need to decide who owns our airflow fork - maybe a 3-person triumvirate?

**Comment by schnie** [comment]
We also need to start upstreaming our fixes to Apache Airflow so we can get Apache committer status. Again, Maxime recommended that the quickest way is to push all PRs as a single user.

**Comment by tedmiston** [comment]
@schnie Agreed.  I would like for us to start making issues so we prioritize the upstreaming wrt other tasks.  It takes a decent amount of effort with back/forth communication on Jira and GitHub to get PRs all the way through over there.  We should discuss this more today if you have time.

**Pull request merged**
