### PR TITLE
Add Hotjar

### PR DESCRIPTION
**Pull request by tedmiston**
Just looking to get Hotjar into our Airflow dashboard internally to get a better idea of how people use it.  Eventually I'll make this work via analytics.js but this was the MVP version just to get the data flowing.

(This isn't something we'd ever upstream but I'd just like to run it on our fork internally.)

### CODE REVIEW

**Comment by tedmiston** [comment]
@perryao Do you see any issues with merging + deploying this today?  I plan to get it in with my prod deploy this evening.

**Comment by perryao** [comment]
Should be fine. Only affects the web server so any potential issues are minimal.

**Comment by perryao** [comment]
@tedmiston were you waiting for me to merge or for other things to get worked out?

**Comment by tedmiston** [comment]
Not waiting on anything specific at this point besides hoping to get a workaround for the PythonOperator / pickling issue in place in docker-airflow first before changing anything else in staging / prod.

**Pull request merged**
